# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vishwas Navada K's Blog
email: hi@vishwas.tech
description: >- # this means to ignore newlines until "baseurl:"
  I am an IT Professional currently working in Infosys Ltd. 
  I have my interest in Programming, Data Visualization and UI Development. 
  I take pictures in free time.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://vishwas.tech" # the base hostname & protocol for your site, e.g. http://example.com
production_url : http://vishwas.tech/blog/
BASE_PATH : http://vishwas.tech/blog/
social_media: vishwasnavadak
metakeywords: vishwas navada k, vishwasnavadak, vishwas github page, vishwas.tech, personal portfolio, webception, web developer, udupi, saligrama
author: Vishwas
# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-redirect-from

remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
